version: '3.7'

services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  nestjs-api:
    # There is a dockerhub image: jassuwu/notesapi-nestjs
    image: jassuwu/notesapi-nestjs
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgresql

volumes:
  db:
    driver: local
